apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  namespace: 4al1-groupe-1
  labels:
    app.kubernetes.io/component: controller
  name: api-ingress-class
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  namespace: 4al1-groupe-1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  ingressClassName: api-ingress-class
  tls:
    - hosts:
        - backend.al1.groupe1.jbienvenu.fr
      secretName: api-ingress-tls
  rules:
    - host: backend.al1.groupe1.jbienvenu.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 8080