name: tests

on:
  push:
    branches: [ main, feature/*, fix/* ]
  pull_request:
    branches: [ main, feature/*, fix/* ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Pull project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run mvn test
        run: mvn --batch-mode --update-snapshots test
